### ISSUE TITLE
Facing Issue after building

### ISSUE THREAD

**Issue by rudrasingh99** [neal1991/gshark#18]
Hey,

I build main.go but after it I am facing 
`root@bugdiscloseguy:~/go/src/github.com/neal1991/gshark# go run main.go 
[0000] PANIC GShark: open /root/go/src/github.com/neal1991/gshark/conf/app.ini: no such file or directory
panic: (*logrus.Entry) (0xb99a40,0xc42006c2a0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420086320, 0xc4200812c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/sirupsen/logrus/entry.go:138 +0x2d2
github.com/sirupsen/logrus.(*Entry).Panic(0xc42006c180, 0xc420065c80, 0x1, 0x1)
        /root/go/src/github.com/sirupsen/logrus/entry.go:206 +0xb8
github.com/sirupsen/logrus.(*Entry).Panicln(0xc42006c180, 0xc420065d08, 0x1, 0x1)
        /root/go/src/github.com/sirupsen/logrus/entry.go:301 +0xd5
github.com/neal1991/gshark/settings.init.0()
        /root/go/src/github.com/neal1991/gshark/settings/settings.go:30 +0x179
exit status 2`

Let me know how to resolve them.

Thanks

**Comment by neal1991** [comment]
The app should be set with a config file `app.ini`.  You can rename the `app-template.ini` to `app.ini`.

**Comment by rudrasingh99** [comment]
still facing 
`
[0000] PANIC GShark: unable to open database file
panic: (*logrus.Entry) (0xb99a40,0xc42006c4e0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420086320, 0xc4200812c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/sirupsen/logrus/entry.go:138 +0x2d2
github.com/sirupsen/logrus.(*Entry).Panic(0xc42006c180, 0xc420065c48, 0x1, 0x1)
        /root/go/src/github.com/sirupsen/logrus/entry.go:206 +0xb8
github.com/sirupsen/logrus.(*Entry).Panicln(0xc42006c180, 0xc420065d28, 0x1, 0x1)
        /root/go/src/github.com/sirupsen/logrus/entry.go:301 +0xd5
github.com/neal1991/gshark/models.init.0()
        /root/go/src/github.com/neal1991/gshark/models/models.go:46 +0x415
exit status 2
`

**Comment by neal1991** [comment]
It is related to the database config. You should check the config in app.ini and make sure you have config correctly.
