### ISSUE TITLE
实现角色用户权限分离

### ISSUE THREAD

**Issue by pt00ls** [neal1991/gshark#32]
如同时给A、B用户开通了一个管理权限账号（都有规则管理、仓库管理、github搜索结果管理权限），如何casbin权限控制A、B用户用户看到与操作的数据？

**Comment by neal1991** [comment]
数据好像是不能控制的，至少我这个不能，我这个权限控制还是比较基础的，主要是针对于访问url的，或许你可以进一步改造下

**Comment by hsluoyz** [comment]
@pt00ls  如果数据操作本身体现到URL上，比如``规则管理、仓库管理、github搜索结果管理``都有不同的URL，那么现在这个权限管理就可以，改下策略就能用。

如果不行的话，只能把Casbin的接口从URL控制层面改到数据层面，也就是所有数据访问都经过Casbin过滤，这个做法可以参考：https://github.com/LyricTian/gin-admin

**Comment by pt00ls** [comment]
好的，非常感谢了。
