### ISSUE TITLE
运行scan 报错

### ISSUE THREAD

**Issue by iliuyongkang** [neal1991/gshark#55]
编译好后，运行scan 报错，运行web正常，报错信息如下：
[0000]  INFO GShark: sqlite db: /home/york//misec.db
[0000]  INFO GShark: all scan mode
[0000]  WARN GShark: There is no valid gitlab token
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d0 pc=0xb6fb96]

goroutine 1 [running]:
github.com/neal1991/gshark/util/gitlabsearch.GetProjects(0x0)
        /home/york/goProject/src/github.com/neal1991/gshark/util/gitlabsearch/search.go:225 +0x356
github.com/neal1991/gshark/util/gitlabsearch.RunSearchTask(0xc0002f5080, 0x0, 0x0)
        /home/york/goProject/src/github.com/neal1991/gshark/util/gitlabsearch/search.go:41 +0x42
github.com/neal1991/gshark/util/gitlabsearch.RunTask(0x384)
        /home/york/goProject/src/github.com/neal1991/gshark/util/gitlabsearch/search.go:15 +0x2b
github.com/neal1991/gshark/util.Scan(0xc0002d26e0)
        /home/york/goProject/src/github.com/neal1991/gshark/util/scan.go:54 +0x24c
github.com/urfave/cli.HandleAction(0xd0b160, 0xee8a10, 0xc0002d26e0, 0xc0002c4c00, 0x0)
        /home/york/goProject/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0xea10ea, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xebd19a, 0x1e, 0x0, ...)
        /home/york/goProject/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc000269380, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /home/york/goProject/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
        /home/york/goProject/src/github.com/neal1991/gshark/main.go:24 +0x354

**Comment by neal1991** [comment]
需要配置一下 gitlab token

**Comment by iliuyongkang** [comment]
好吧，我看到只是一个警告，还以为不是那个引起的
