### ISSUE TITLE
无法获取gitlab和github上的仓库进行扫描

### ISSUE THREAD

**Issue by Bingoohyb** [neal1991/gshark#57]
你好：
目前发现有一些问题：
1、当我录入github上的token后，后台执行./main scan命令时，会提示以下信息

[0000]  INFO GShark: Init rules, err: <nil>
[0000]  INFO GShark: all scan mode
[0000]  WARN GShark: There is no valid gitlab token
[0000]  INFO GShark: Complete the scan of Gitlab, start to sleep 15m0s seconds

为何会提示gitlab token呢？

2、当我使用gitlab token后，后台执行./main scan命令时，会提示以下信息，导致无法运行

[root@localhost gshark]# ./main scan
[0000]  INFO GShark: Init rules, err: <nil>
[0000]  INFO GShark: all scan mode
Get https://gitlab.com/api/v4/projects?page=1&per_page=100: dial tcp: lookup gitlab.com on 114.114.114.114:53: read udp 192.168.100.197:50849->114.114.114.114:53: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb6f9eb]

goroutine 1 [running]:
github.com/neal1991/gshark/util/gitlabsearch.GetProjects(0xc0002ee000)
	/home/gshark/util/gitlabsearch/search.go:253 +0x31b
github.com/neal1991/gshark/util/gitlabsearch.RunSearchTask(0xc0002a5b60, 0x0, 0x0)
	/home/gshark/util/gitlabsearch/search.go:44 +0x4b
github.com/neal1991/gshark/util/gitlabsearch.RunTask(0x384)
	/home/gshark/util/gitlabsearch/search.go:15 +0x2b
github.com/neal1991/gshark/util.Scan(0xc000267a20)
	/home/gshark/util/scan.go:54 +0x24c
github.com/urfave/cli.HandleAction(0xd0afe0, 0xee8870, 0xc000267a20, 0xc00007b000, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0xea0f6a, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xebcffe, 0x1e, 0x0, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc0001cf380, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
	/home/gshark/main.go:24 +0x354

3、请问是否只能使用公网的github与gitlab呢？请问后续是否会支持本地的gitlab？

build时未报错，以下为运行web端时的提示，不知道是否有影响，数据库我见已有内容

[root@localhost gshark]# ./main web
[0001]  INFO GShark: Init rules, err: <nil>
[0001]  INFO GShark: Init filter rules, err: <nil>
[0001]  INFO GShark: Server is running on 127.0.0.1:8000

麻烦您看下，谢谢

**Comment by neal1991** [comment]
github 和 gitlab 使用不同的token的，建议如果需要gitlab的话可以添加token，不过目前gitlab不是特别稳定，好像还有点问题。
目前应该不支持本地的 gitlab，但改一下应该不难。
其实可以通过修改 mode改变搜索的类型，`./main --mode github` 只会搜索github

**Comment by xj90512** [comment]
> github 和 gitlab 使用不同的token的，建议如果需要gitlab的话可以添加token，不过目前gitlab不是特别稳定，好像还有点问题。 目前应该不支持本地的 gitlab，但改一下应该不难。 其实可以通过修改 mode改变搜索的类型，`./main --mode github` 只会搜索github

想了解下，如果要支持本地gitlab的支持，需要怎么调整，增加一个本地域名的配置还是需要去改源代码啊？
谢谢。

**Comment by madneal** [comment]
需要配置 gitlab 的 token，mode 可以使用 gitlab，不过由于 gitlab api限制，效率是非常低的

**Comment by xj90512** [comment]
> 需要配置 gitlab 的 token，mode 可以使用 gitlab，不过由于 gitlab api限制，效率是非常低的

看了下源代码和go-gitlab，发现是支持配置本地gitlab的域名的，需要修改search.go

**Comment by xj90512** [comment]
> 不需要修改源码

git, err := gitlab.NewClient("yourtokengoeshere", gitlab.WithBaseURL("https://git.mydomain.com/api/v4"))
if err != nil {
  log.Fatalf("Failed to create client: %v", err)
}
users, _, err := git.Users.ListUsers(&gitlab.ListUsersOptions{})
